using System.ComponentModel.DataAnnotations;

namespace DapperMvcDemo.Data.Models.Domain
{
    public class Person
    {
        public int Id { get; set; } // Auto-generated by the database (IDENTITY)

        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; } = string.Empty;

        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Invalid email format")]
        public string Email { get; set; } = string.Empty;

        public string Address { get; set; } = string.Empty;
    }
}
